### ISSUE TITLE
 is Gaussian blurring a non-linear operation?

### ISSUE THREAD

**Issue by ibrhmyzc** [hamzayogurtcuoglu/openCV#1]
the question is in the title

**Comment by hamzayogurtcuoglu** [comment]
Hi Mr. Yazıcı,

We classify whether an operator is linear according to the following
features :
1) Shift Invariant
2) Additivity
3) Separable
gauss provides these 3 features

Best regards,

Hamza YOĞURTCUOĞLU




ibrhmyzc <notifications@github.com>, 4 Şub 2020 Sal, 20:32 tarihinde şunu
yazdı:

**Comment by ibrhmyzc** [comment]
Herr. Yogurtcuoglu Ich danke Ihnen von Herzen für Ihre Unterstützung!
